plugins {
    id 'com.android.application'
}

android {
    namespace 'vn.yhct.club'
    compileSdk 35

    defaultConfig {
        applicationId 'vn.yhct.club'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '3.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
